In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv('house_prices.csv', usecols = colunas_usadas)

In [6]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [8]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [11]:
X = base.drop('price', axis = 1)
y = base.price

In [12]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [13]:
type(X)

pandas.core.frame.DataFrame

In [14]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [15]:
type(y)

pandas.core.series.Series

In [16]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [17]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [18]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [19]:
print(colunas[10])

NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [20]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [21]:
X_treinamento.shape

(15129, 16)

In [22]:
y_treinamento.shape

(15129,)

In [23]:
X_teste.shape

(6484, 16)

In [24]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [25]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste,
                                                   batch_size = 32, num_epochs = 10000, shuffle = False)

In [26]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmp5bgrd_pa', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [27]:
regressor.train(input_fn=funcao_treinamento, steps = 10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Please use `layer.add_weight` method instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmp5bgrd_pa/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving c

INFO:tensorflow:global_step/sec: 212.387
INFO:tensorflow:loss = 0.012748381, step = 4201 (0.475 sec)
INFO:tensorflow:global_step/sec: 211.736
INFO:tensorflow:loss = 0.009725157, step = 4301 (0.471 sec)
INFO:tensorflow:global_step/sec: 199.939
INFO:tensorflow:loss = 0.014850413, step = 4401 (0.498 sec)
INFO:tensorflow:global_step/sec: 194.053
INFO:tensorflow:loss = 0.041254636, step = 4501 (0.513 sec)
INFO:tensorflow:global_step/sec: 214.64
INFO:tensorflow:loss = 0.027635455, step = 4601 (0.469 sec)
INFO:tensorflow:global_step/sec: 199.473
INFO:tensorflow:loss = 0.09138587, step = 4701 (0.500 sec)
INFO:tensorflow:global_step/sec: 200.465
INFO:tensorflow:loss = 0.009720525, step = 4801 (0.495 sec)
INFO:tensorflow:global_step/sec: 202.059
INFO:tensorflow:loss = 0.008907655, step = 4901 (0.504 sec)
INFO:tensorflow:global_step/sec: 192.903
INFO:tensorflow:loss = 0.007567077, step = 5001 (0.510 sec)
INFO:tensorflow:global_step/sec: 192.99
INFO:tensorflow:loss = 0.01896659, step = 5101 (0.522

In [28]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-08-06T17:38:09Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmp5bgrd_pa/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Inference Time : 49.58649s
INFO:tensorflow:Finished evaluation at 2020-08-06-17:38:59
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007865445, global_step = 10000, label/mean = 0.061511144, loss = 0.025169425, prediction/mean = 0.0

In [29]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-08-06T17:39:01Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmp5bgrd_pa/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Inference Time : 45.71770s
INFO:tensorflow:Finished evaluation at 2020-08-06-17:39:47
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00064313185, global_step = 10000, label/mean = 0.059815314, loss = 0.02058022, prediction/mean = 0.0

In [30]:
metricas_treinamento

{'average_loss': 0.0007865445,
 'label/mean': 0.061511144,
 'loss': 0.025169425,
 'prediction/mean': 0.055526294,
 'global_step': 10000}

In [31]:
metricas_teste

{'average_loss': 0.00064313185,
 'label/mean': 0.059815314,
 'loss': 0.02058022,
 'prediction/mean': 0.054628216,
 'global_step': 10000}

In [32]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [33]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [34]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmp5bgrd_pa/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.05606408], dtype=float32)},
 {'predictions': array([0.00496203], dtype=float32)},
 {'predictions': array([0.04553603], dtype=float32)},
 {'predictions': array([0.13306808], dtype=float32)},
 {'predictions': array([0.04739781], dtype=float32)},
 {'predictions': array([0.00345269], dtype=float32)},
 {'predictions': array([0.02232587], dtype=float32)},
 {'predictions': array([0.14658645], dtype=float32)},
 {'predictions': array([0.04454591], dtype=float32)},
 {'predictions': array([0.05839607], dtype=float32)},
 {'predictions': array([0.09283639], dtype=float32)},
 {'predictions': array([0.03841777], dtype=float32)},
 {'predictions': array([0.16754264], dtype=float32)},
 {'predictions': array([0.03870181], dtype=float32)},
 {'predictions': array([0.08088125], dtype=float32)},
 {'predictions': array([0.03304312], dtype=float32)},
 {'predictions': array([0.00616077], dtype=float32)},
 {'predictions': array([0.05985633], dtype=float32)},
 {'predictions': array([0.01

In [35]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmp5bgrd_pa/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [36]:
valores_previsoes

[array([0.05606408], dtype=float32),
 array([0.00496203], dtype=float32),
 array([0.04553603], dtype=float32),
 array([0.13306808], dtype=float32),
 array([0.04739781], dtype=float32),
 array([0.00345269], dtype=float32),
 array([0.02232587], dtype=float32),
 array([0.14658645], dtype=float32),
 array([0.04454591], dtype=float32),
 array([0.05839607], dtype=float32),
 array([0.09283639], dtype=float32),
 array([0.03841777], dtype=float32),
 array([0.16754264], dtype=float32),
 array([0.03870181], dtype=float32),
 array([0.08088125], dtype=float32),
 array([0.03304312], dtype=float32),
 array([0.00616077], dtype=float32),
 array([0.05985633], dtype=float32),
 array([0.01651721], dtype=float32),
 array([0.06722875], dtype=float32),
 array([0.0358903], dtype=float32),
 array([0.0117536], dtype=float32),
 array([0.05295214], dtype=float32),
 array([0.0163835], dtype=float32),
 array([0.02679785], dtype=float32),
 array([0.03407715], dtype=float32),
 array([0.00906309], dtype=float32),
 arr

In [37]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [38]:
valores_previsoes

array([[0.05606408],
       [0.00496203],
       [0.04553603],
       ...,
       [0.04821292],
       [0.0624207 ],
       [0.03810336]], dtype=float32)

In [39]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[502488.62],
       [112835.45],
       [422212.22],
       ...,
       [442623.5 ],
       [550957.8 ],
       [365538.1 ]], dtype=float32)

In [40]:
y_teste

12555    0.071224
5119     0.030820
18354    0.061639
8807     0.127869
502      0.035016
           ...   
19447    0.030820
11355    0.093770
2047     0.059410
17244    0.080656
2971     0.042623
Name: price, Length: 6484, dtype: float64

In [41]:
y_teste.shape

(6484,)

In [42]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [43]:
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [44]:
y_teste2

array([[618080.],
       [310000.],
       [545000.],
       ...,
       [528000.],
       [690000.],
       [400000.]])

In [45]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [46]:
mae

124895.99674918606